"""
Django settings for fishcurrent project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import dj_database_url

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-fallback-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize', # Added for 'humanize' template tags
    
    # Third party
    'tailwind',
    'market',
    'widget_tweaks',

    # Local Apps
    'core',
    'users',
    'store',
    'orders',
    'chat',
    'notifications',
    'custom_admin',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'fishcurrent.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'store.context_processors.cart',
                'notifications.context_processors.unread_notifications',
            ],
        },
    },
]

WSGI_APPLICATION = 'fishcurrent.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

import sys
import dj_database_url

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

database_url = os.getenv('DATABASE_URL')

if database_url:
    # Clean up the URL
    database_url = database_url.strip()
    
    # Handle accidentally pasted psql command (e.g. "psql 'postgresql://...'")
    if database_url.startswith("psql"):
        parts = database_url.split()
        if len(parts) > 1:
            database_url = parts[1]
    
    # Handle quoted strings just in case
    if database_url.startswith('"') and database_url.endswith('"'):
        database_url = database_url[1:-1]
    elif database_url.startswith("'") and database_url.endswith("'"):
        database_url = database_url[1:-1]
    
    # Fix HTML entities that might be copied from web interfaces
    # Common when copying from Neon, Heroku, or other dashboards
    database_url = database_url.replace('&amp;', '&')
    database_url = database_url.replace('&lt;', '<')
    database_url = database_url.replace('&gt;', '>')
    database_url = database_url.replace('&quot;', '"')
    
    print(f"Render Debug: Processing DATABASE_URL. Length: {len(database_url)}", file=sys.stderr)
    print(f"Render Debug: Start of URL: {database_url[:15]}...", file=sys.stderr)

    # Convert postgresql:// to postgres:// implementation if needed
    if database_url.startswith('postgresql://'):
        database_url = database_url.replace('postgresql://', 'postgres://', 1)
    
    try:
        db_config = dj_database_url.parse(database_url, conn_max_age=600)
        DATABASES['default'] = db_config
        print("Render Debug: Successfully configured database.", file=sys.stderr)
    except Exception as e:
        print(f"Render Critical: Failed to parse DATABASE_URL: {e}", file=sys.stderr)
        # Fallback to sqlite is already set above



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'market' / 'static',
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media Configuration
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Tailwind Configuration
TAILWIND_APP_NAME = 'market'

INTERNAL_IPS = [
    "127.0.0.1",
]

# Auth User Model
AUTH_USER_MODEL = 'users.User'

# PayMongo Keys (Accessible in settings)
PAYMONGO_SECRET_KEY = os.getenv('PAYMONGO_SECRET_KEY')
PAYMONGO_PUBLIC_KEY = os.getenv('PAYMONGO_PUBLIC_KEY')

# Cart Session ID
CART_SESSION_ID = 'cart'

# Login Redirects
LOGIN_URL = 'users:login'
LOGIN_REDIRECT_URL = 'store:product_list'
LOGOUT_REDIRECT_URL = 'store:product_list'


