services:
  - type: web
    name: fishcurrent
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn fishcurrent.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      # DATABASE_URL should be set manually in Render Dashboard for Neon DB
